title               : iamtejas
description         : >-
                     "The world is full of magical things, 
                      patiently waiting for our senses to grow sharper."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
remote_theme        : tejasvaidhyadev/portfolYOU       # theme 

### Plugins ###
plugins:
  - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following path is excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  



### Author Info ###
author:
  name              : Tejas Vaidhya
  image             : https://raw.githubusercontent.com/tejasvaidhyadev/tejasvaidhyadev.github.io/master/_images/tejas.jpg
# behance           : your_username
# dribbble          : your_username
  email             : iamtejasvaidhy@gmail.com
  facebook          : tejas.vaidhya.52
  github            : tejasvaidhyadev
# gitlab            : your_username
  instagram         : tejasvaidhya/
  linkedin          : tejas-vaidhya-0245b5157/
  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_namef

### Disqus
disqus: portfolio-bnhbmol6a5


### Posts ###
permalink: /blog/:title

markdown: kramdown
kramdown:
   math_engine: mathjax

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "posts"                                  
    values:
      comments: true
      
### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

gems:
  - jekyll-sitemap

